version: '3'

services:
  postgres:
    image: postgres
    container_name: postgres
    ports:
    - 5432:5432
    environment:
      - POSTGRES_USER=wanted
      - POSTGRES_PASSWORD=wantedps
      - POSTGRES_DB=wanted_db



  app:
    container_name: app
    depends_on:
      - postgres
    ports:
      - 80:8080
    build:
      context: .
      dockerfile: ./docker/go/Dockerfile
    environment:
      - GOPATH=/go
    volumes:
      - ./go:/go/src/app/go/
    command: go run main.go